name: Lint, Test & Deploy
on: [push, workflow_dispatch]
jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - &checkout
              name: Get Code from Repo
              uses: actions/checkout@v4
            - &InstallNodeJS
              name: Install Node JS
              uses: actions/setup-node@v3
              with:
                node-version: 18
            - &InstallDependencies
              name: Install Dependencies
              run: npm ci
            - name: Run Lint
              run: npm run lint
    test:
        needs: lint
        runs-on: ubuntu-latest
        steps:
            - *checkout
            - *InstallNodeJS
            - *InstallDependencies
            - name: Run Test
              run: npm test
    deploy:
        needs: test
        runs-on: ubuntu-latest
        steps:
            - *checkout
            - *InstallNodeJS
            - *InstallDependencies
            - name: Deploy to Server
              run: echo "Deploying To Server!!"